### ISSUE TITLE
slow lcov format-coverage 

### ISSUE THREAD

**Issue by granth** [codeclimate/test-reporter#264] opened 2017-11-26 20:06 UTC
`cc-test-reporter format-coverage` takes 3 minutes to process my `coverage/lcov.info` file.

The old test reporter takes 2 seconds to upload the coverage file, so this is not quite as good.

The debug output is mostly lines like:

```
INFO[0179] triming with prefix /home/ubuntu/4ormat/
    
DEBU[0179] getting git blob_id for source file format-modules/video-asset-modal/src/components/inner.js 
```

The `lcov.info` is generated by Istanbul. Is there anything I can change about it that will help `format-coverage`?

This is running on CircleCI 1.

**Comment by wfleming** [comment] 2017-12-04 19:49
@granth thanks for the report, sorry for the poor performance.

Is the project you're working with OSS by any chance? We can try and reproduce independently, of course, but it might go faster if you're able to share the the repo or test `lcov.info` file that's specifically causing your problems.

**Comment by granth** [comment] 2017-12-04 21:24
@wfleming No, I'm afraid it isn't. I can probably send you an `lcov.info` privately.

**Comment by wfleming** [comment] 2017-12-06 22:28
@granth I've caught a couple of pieces of low-hanging fruit just doing some code review, and have opened a PR (#270) with my work in progress. I wrote a small benchmark on that PR as well, but unfortunately none of the easy stuff I've already caught has shifted the needle on the benchmark much, so the bottleneck affecting you probably isn't either of the things I noticed.

If you're comfortable sharing your `lcov.info` privately, I'd appreciate that as it would hopefully help know where to focus my efforts via some profiling. You can email me at will@codeclimate.com if you're ok with that.

If it makes it easier for you, I also hacked up this little python script to sanitize a `lcov.info` by anonymizing file & function names within the report, since I doubt those specifics are part of the bottleneck:

```
#!/usr/bin/env python

import re
import sys

fileCount = 0
funCount = 0

FILE_LINE = re.compile("^SF:.*$")
FN_LINE = re.compile("^FN:(\d+),.*$")
FNDA_LINE = re.compile("^FNDA:(\d+),.*$")

f = open(sys.argv[1], "r")
for line in f:
  m = FILE_LINE.match(line)
  if m:
    print("SF:file_{}".format(fileCount))
    fileCount += 1
  else:
    m = FN_LINE.match(line)
    if m:
      print("FN:{},function_{}".format(m.group(1), funCount))
      funCount += 1
    else:
      m = FNDA_LINE.match(line)
      if m:
        print("FNDA:{},function_{}".format(m.group(1), funCount))
        funCount += 1
      else:
        sys.stdout.write(line)
```

**Comment by wfleming** [comment] 2018-01-08 21:34
@granth we released version 0.4.1 with some performance improvements we were able to identify to the lcov formatter. If you're using our recommended docs to download the client in your CI you should get this latest version automatically. Please let me know if you're still seeing unacceptably slow performance.

**Comment by granth** [comment] 2018-01-08 21:50
🎉 📉 huge difference! `format-coverage` now takes 2 s.

Thanks!

**Comment by wfleming** [comment] 2018-01-09 17:00
Glad to hear it! I'm always happy when I can measure performance improvements in orders of magnitude 😄. I'm going to close this issue now since I think your issue is resolved, please let me know if that's not correct.

**Closed by wfleming** 2018-01-09 17:00 UTC
