### ISSUE TITLE
test reporter broke

### ISSUE THREAD

**Issue by coding-bunny** [codeclimate/test-reporter#418] opened 2020-01-28 13:28 UTC
I have no idea what changed, because I'm always pulling the latest version from the net, but since today my tests are failing because of a problem with the cc-test-reporter:

```
#!/bin/bash -eo pipefail
./cc-test-reporter before-build
bundle exec rspec \
--profile 10 \
--require rspec_junit_formatter \
--out tmp/test-results/rspec/rspec.xml \
--format progress
./cc-test-reporter format-coverage -t simplecov -o tmp/test-results/codeclimate.inkycop.json coverage/.resultset.json

........................

Top 10 slowest examples (0.04535 seconds, 56.0% of total time):
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the coverage path
    0.00546 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:90
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the doc path
    0.00487 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:98
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the tmp path
    0.00481 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:114
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the log path
    0.00471 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:102
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml enables csslint
    0.00445 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:47
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the script path
    0.00439 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:110
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml targets the right rubocop version
    0.00433 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:85
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the public path
    0.00428 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:106
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the vendor path
    0.00417 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:118
  Inkycop::InstallGenerator without arguments #create_root_codeclimate_yml excludes the db path
    0.00389 seconds ./spec/lib/generators/inkycop/install_generator_spec.rb:94

Top 2 slowest example groups:
  Inkycop::InstallGenerator
    0.00343 seconds average (0.07881 seconds / 23 examples) ./spec/lib/generators/inkycop/install_generator_spec.rb:8
  Inkycop
    0.00093 seconds average (0.00093 seconds / 1 example) ./spec/inkycop_spec.rb:3

Finished in 0.08104 seconds (files took 0.49564 seconds to load)
24 examples, 0 failures

Coverage report generated for RSpec to /home/circleci/inkycop/coverage. 82 / 82 LOC (100.0%) covered.
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-test-reporter format-coverage [coverage file] [flags]

Flags:
      --add-prefix string   add this prefix to file paths
  -t, --input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --prefix string       the root directory where the coverage analysis was performed (default "/home/circleci/inkycop")

Global Flags:
  -d, --debug   run in debug mode


Exited with code exit status 255
```

This was working fine on previous runs, but all of a sudden this is now broken on our circle-ci

**Comment by coding-bunny** [comment] 2020-01-28 15:12
This seems to be related to the new simplecov 0.18 release.
Will a fix be made to keep supporting this framework?

**Comment by steveh** [comment] 2020-01-28 19:53
Same issue for me - crops up with a PR to upgrade SimpleCov to 0.18.

[Changelog](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md#0180-2020-01-28)

**Comment by steveh** [comment] 2020-01-28 19:54
oops, duplicate of #413 probably

**Comment by coding-bunny** [comment] 2020-01-28 20:51
yes, it's the 0.18 release that's causing it with the changes in the file.
The test-runner simply cannot seem to handle this and crashes completely with some parsing error.
Since this blocks all our builds at the moment on Circle that are using SimpleCov, we either need to freeze to v0.17 in the meanwhile or live with broken builds till the cc-test-runner works.

**Comment by coding-bunny** [comment] 2020-01-30 09:37
Can we get any feedback/updates regarding this issue?
From the excessive amount of links to this issue, major projects are being impacted by this.

**Comment by efueger** [comment] 2020-01-30 18:40
Hi @coding-bunny - Emily here with Code Climate Support. Thanks for opening the issue.

And you're correct: our test reporter is having trouble with SimpleCov's newest 0.18+ release. 
- We're in [active comms](https://github.com/codeclimate/test-reporter/issues/413) with the Maintainer now, and hope to have a solution in place soon. 👍
- In the meantime, the workaround is to use SimpleCov 0.17.x in your testing setup.

Thanks again I'll be in touch here with any progress. 

Feel free to drop us a line at hello@codeclimate.com with any other specific setup questions and we'll be happy to help.

**Comment by pirj** [comment] 2020-02-02 19:54
Nice, thank you @koic!

@coding-bunny Can you please retrigger the builds?

**Comment by coding-bunny** [comment] 2020-02-02 20:48
Will do so first thing tomorrow morning when I'm in the office and report back with any findings/successes

**Comment by coding-bunny** [comment] 2020-02-03 07:44
The comment seems to have been deleted, but I've triggered the builds again on our CI system.
However, the test reporter is still not working:

```
#!/bin/bash -eo pipefail
cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"

Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
Usage:
  cc-****-reporter format-coverage [coverage file] [flags]

Flags:
      --add-prefix string   add this prefix to file paths
  -t, --input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
  -o, --output string       output path (default "coverage/codeclimate.json")
  -p, --prefix string       the root directory where the coverage analysis was performed (default "/root/customink-for-business")

Global Flags:
  -d, --debug   run in debug mode


Exited with code exit status 255
```

**Comment by pirj** [comment] 2020-02-03 09:07
@coding-bunny I'm totally sorry for your time, I've commented in a different repository and deleted the comment when noticed my mistake.

**Comment by coding-bunny** [comment] 2020-02-03 09:41
no worries :D
Just keeping our PR's on hold for the Simplecov upgrade until this tool works again.

**Comment by ivobenedito** [comment] 2020-06-18 14:44
Is there any expectation when will the cc-test-reporter be fixed? Thanks

**Comment by danielnc** [comment] 2020-06-19 21:21
Bump

When can we get this fixed?

**Comment by smith558** [comment] 2020-07-09 14:24
Ping, the issue still present

**Comment by compwron** [comment] 2020-07-30 08:35
Is there any progress on this issue? I am having this problem also.

**Comment by aliuk2012** [comment] 2020-08-17 10:51
Still seems to be an issue with SimpleCov 0.19.0

**Comment by efueger** [comment] 2020-08-19 19:56
Hi all - thanks for your patience here! We're working with Simplecov's maintainer for supporing 0.18+ and hope to have a fix in place soon.

Closing this thread, but feel free to follow along [here](https://github.com/codeclimate/test-reporter/issues/413).

**Closed by efueger** 2020-08-19 19:56 UTC

**Comment by fedegl** [comment] 2021-07-24 00:14
I am using the latest version of cc-test-reporter and Simplecov 0.21.2 and still experiencing the issue. Anyone else experiencing this?

**Comment by Mehonoshin** [comment] 2021-11-07 14:15
Still an issue for me(simplecov-0.21.2)

**Comment by niclas-ahden** [comment] 2021-12-10 16:50
@fedegl @Mehonoshin @maurolscla 0.21.2 is working for us. However, we did get this issue before setting `CC_TEST_REPORTER_ID`, so I'd look into that 👌

https://github.com/simplecov-ruby/simplecov/#json-formatter says:
>_Note:_ In case you plan to report your coverage results to CodeClimate services, know that SimpleCov will automatically use the JSON formatter along with the HTML formatter when the `CC_TEST_REPORTER_ID` variable is present in the environment.

Here's how to find your reporter ID: https://docs.codeclimate.com/docs/finding-your-test-coverage-token

Hope it works out!

**Comment by gregorw** [comment] 2022-04-06 22:57
Slight different error message that I am getting (with all the latest versions):

```
Error: json: cannot unmarshal object into Go struct field resultSet.coverage of type []formatters.NullInt
```

**Comment by BobbyMcWho** [comment] 2022-06-03 03:52
If anyone comes across this via Google, and you're using the `paambaati/codeclimate-action` GitHub Action to upload your coverage, make sure you set `CC_TEST_REPORTER_ID` in both the action, as well as the ENV for the test run, and make sure you update your coverageLocations (your paths may vary)
```diff
coverageLocations: |
-  ${{github.workspace}}/coverage/coverage-report-*/.resultset.json:simplecov
+  ${{github.workspace}}/coverage/coverage-report-*/coverage.json:simplecov
```

**Comment by Zeneixe** [comment] 2023-04-20 08:56
We have this error with simplecov 0.22

```
Error: json: cannot unmarshal object into Go struct field resultSet.coverage of type []formatters.NullInt
```

**Comment by ldlgds2** [comment] 2023-08-22 12:02
From: https://docs.codeclimate.com/docs/test-coverage-troubleshooting-tips#section-specific-error-messages-from-the-reporter
Take a look at this:
This error happens when using SimpleCov newer versions (`simplecov >= 0.19`) and the reporter is not able to parse the default SimpleCov formatter, you need to set up the JSON one.

Ensure that the `CC_TEST_REPORTER_ID` variable is present in the environment when you run the test suite. This will force SimpleCov to automatically use the JSON formatter along with the HTML formatter.

References:
- [this comment](https://github.com/simplecov-ruby/simplecov#json-formatter) in the SimpleCov README
- [this comment](https://github.com/codeclimate/test-reporter/issues/413#issuecomment-1079155787) in an issue on CodeClimate
